### ISSUE TITLE
In a docker container, 'netpanzer --version' results in segfault about 40 percent of the time

### ISSUE THREAD

**Issue by andy5995** [netpanzer/netpanzer#267]
The server runs fine so far. Up for 30 minutes. I have three bots connected; however...

I'm running a container that has sanitization on. To build the image, I modified part of the [config in our Dockerfile](https://github.com/netpanzer/netpanzer/blob/ad1c9ab927c5f9644b443fbba91e1c468c4b595d/support/docker/Dockerfile):

```
RUN \
  cd /netpanzer && \
  ./setup-build.sh _build \
    -Dprefix=/usr \
    -Dbuildtype=debug && \
  cd _build && \
  ninja && \
  meson install --skip-subprojects
```

This issue doesn't happen when I try to reproduce in my regular build directory on Manjaro.

```
npserver@26dfc3e057de:~$ netpanzer --version
2024-11-13 03:44:04 localeDir: /usr/share/locale

NetPanzer version 0.9.0-rc8-dev
Copyright(c) 1998 Pyrosoft Inc. & NetPanzer Development Team
npserver@26dfc3e057de:~$ netpanzer --version
2024-11-13 03:44:05 localeDir: /usr/share/locale

NetPanzer version 0.9.0-rc8-dev
Copyright(c) 1998 Pyrosoft Inc. & NetPanzer Development Team
npserver@26dfc3e057de:~$ netpanzer --version
2024-11-13 03:44:06 localeDir: /usr/share/locale

NetPanzer version 0.9.0-rc8-dev
Copyright(c) 1998 Pyrosoft Inc. & NetPanzer Development Team
npserver@26dfc3e057de:~$ netpanzer --version
AddressSanitizer:DEADLYSIGNAL
AddressSanitizer:DEADLYSIGNAL
AddressSanitizer:DEADLYSIGNAL
AddressSanitizer:DEADLYSIGNAL
AddressSanitizer:DEADLYSIGNAL
AddressSanitizer:DEADLYSIGNAL
AddressSanitizer:DEADLYSIGNAL
Segmentation fault (core dumped)
```

## gdb

Nothing useful I see from gdb.

```
(gdb) run --version
Starting program: /usr/bin/netpanzer --version
warning: Error disabling address space randomization: Operation not permitted
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
==3221==AddressSanitizer: failed to intercept '__isoc99_printf'
'==3221==AddressSanitizer: failed to intercept '__isoc99_sprintf'
'==3221==AddressSanitizer: failed to intercept '__isoc99_snprintf'
'==3221==AddressSanitizer: failed to intercept '__isoc99_fprintf'
'==3221==AddressSanitizer: failed to intercept '__isoc99_vprintf'
'==3221==AddressSanitizer: failed to intercept '__isoc99_vsprintf'
'==3221==AddressSanitizer: failed to intercept '__isoc99_vsnprintf'
'==3221==AddressSanitizer: failed to intercept '__isoc99_vfprintf'
'==3221==AddressSanitizer: failed to intercept 'pthread_mutexattr_getrobust_np'
'==3221==AddressSanitizer: failed to intercept 'xdr_quad_t'
'==3221==AddressSanitizer: failed to intercept 'xdr_u_quad_t'
'==3221==AddressSanitizer: failed to intercept 'xdr_destroy'
'==3221==AddressSanitizer: failed to intercept 'crypt'
'==3221==AddressSanitizer: failed to intercept 'crypt_r'
'==3221==AddressSanitizer: libc interceptors initialized
|| `[0x10007fff8000, 0x7fffffffffff]` || HighMem    ||
|| `[0x02008fff7000, 0x10007fff7fff]` || HighShadow ||
|| `[0x00008fff7000, 0x02008fff6fff]` || ShadowGap  ||
|| `[0x00007fff8000, 0x00008fff6fff]` || LowShadow  ||
|| `[0x000000000000, 0x00007fff7fff]` || LowMem     ||
MemToShadow(shadow): 0x00008fff7000 0x000091ff6dff 0x004091ff6e00 0x02008fff6fff
redzone=16
max_redzone=2048
quarantine_size_mb=256M
thread_local_quarantine_size_kb=1024K
malloc_context_size=30
SHADOW_SCALE: 3
SHADOW_GRANULARITY: 8
SHADOW_OFFSET: 0x7fff8000
==3221==Installed the sigaction for signal 11
==3221==Installed the sigaction for signal 7
==3221==Installed the sigaction for signal 8
==3221==T0: stack [0x7ffc961d2000,0x7ffc969d2000) size 0x800000; local=0x7ffc969d0494
==3221==AddressSanitizer Init done
2024-11-13 03:39:21 localeDir: /usr/share/locale

[New Thread 0x7a387fe00640 (LWP 3222)]
==3221==T1: stack [0x7a387f601000,0x7a387fdffd40) size 0x7fed40; local=0x7a387fdffc44
NetPanzer version 0.9.0-rc8-dev
Copyright(c) 1998 Pyrosoft Inc. & NetPanzer Development Team
==3223==Could not attach to thread 3221 (errno 1).
==3223==Could not attach to thread 3222 (errno 1).
==3223==Failed suspending threads.
==3221==LeakSanitizer has encountered a fatal error.
==3221==HINT: For debugging, try setting environment variable LSAN_OPTIONS=verbosity=1:log_threads=1
==3221==HINT: LeakSanitizer does not work under ptrace (strace, gdb, etc)
[Thread 0x7a387fe00640 (LWP 3222) exited]
[Inferior 1 (process 3221) exited with code 01]
(gdb) run --version
Starting program: /usr/bin/netpanzer --version
warning: Error disabling address space randomization: Operation not permitted
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
==3224==AddressSanitizer: failed to intercept '__isoc99_printf'
'==3224==AddressSanitizer: failed to intercept '__isoc99_sprintf'
'==3224==AddressSanitizer: failed to intercept '__isoc99_snprintf'
'==3224==AddressSanitizer: failed to intercept '__isoc99_fprintf'
'==3224==AddressSanitizer: failed to intercept '__isoc99_vprintf'
'==3224==AddressSanitizer: failed to intercept '__isoc99_vsprintf'
'==3224==AddressSanitizer: failed to intercept '__isoc99_vsnprintf'
'==3224==AddressSanitizer: failed to intercept '__isoc99_vfprintf'
'==3224==AddressSanitizer: failed to intercept 'pthread_mutexattr_getrobust_np'
'==3224==AddressSanitizer: failed to intercept 'xdr_quad_t'
'==3224==AddressSanitizer: failed to intercept 'xdr_u_quad_t'
'==3224==AddressSanitizer: failed to intercept 'xdr_destroy'
'==3224==AddressSanitizer: failed to intercept 'crypt'
'==3224==AddressSanitizer: failed to intercept 'crypt_r'
'==3224==AddressSanitizer: libc interceptors initialized
|| `[0x10007fff8000, 0x7fffffffffff]` || HighMem    ||
|| `[0x02008fff7000, 0x10007fff7fff]` || HighShadow ||
|| `[0x00008fff7000, 0x02008fff6fff]` || ShadowGap  ||
|| `[0x00007fff8000, 0x00008fff6fff]` || LowShadow  ||
|| `[0x000000000000, 0x00007fff7fff]` || LowMem     ||
MemToShadow(shadow): 0x00008fff7000 0x000091ff6dff 0x004091ff6e00 0x02008fff6fff
redzone=16
max_redzone=2048
quarantine_size_mb=256M
thread_local_quarantine_size_kb=1024K
malloc_context_size=30
SHADOW_SCALE: 3
SHADOW_GRANULARITY: 8
SHADOW_OFFSET: 0x7fff8000
==3224==Installed the sigaction for signal 11
==3224==Installed the sigaction for signal 7
==3224==Installed the sigaction for signal 8
==3224==T0: stack [0x7fffe06ab000,0x7fffe0eab000) size 0x800000; local=0x7fffe0eaa2e4
==3224==AddressSanitizer Init done
2024-11-13 03:39:22 localeDir: /usr/share/locale

[New Thread 0x703813600640 (LWP 3225)]
==3224==T1: stack [0x703812e01000,0x7038135ffd40) size 0x7fed40; local=0x7038135ffc44
NetPanzer version 0.9.0-rc8-dev
Copyright(c) 1998 Pyrosoft Inc. & NetPanzer Development Team
==3226==Could not attach to thread 3224 (errno 1).
==3226==Could not attach to thread 3225 (errno 1).
==3226==Failed suspending threads.
==3224==LeakSanitizer has encountered a fatal error.
==3224==HINT: For debugging, try setting environment variable LSAN_OPTIONS=verbosity=1:log_threads=1
==3224==HINT: LeakSanitizer does not work under ptrace (strace, gdb, etc)
[Thread 0x703813600640 (LWP 3225) exited]
[Inferior 1 (process 3224) exited with code 01]
(gdb) run --version
Starting program: /usr/bin/netpanzer --version
warning: Error disabling address space randomization: Operation not permitted
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
==3227==AddressSanitizer: failed to intercept '__isoc99_printf'
'==3227==AddressSanitizer: failed to intercept '__isoc99_sprintf'
'==3227==AddressSanitizer: failed to intercept '__isoc99_snprintf'
'==3227==AddressSanitizer: failed to intercept '__isoc99_fprintf'
'==3227==AddressSanitizer: failed to intercept '__isoc99_vprintf'
'==3227==AddressSanitizer: failed to intercept '__isoc99_vsprintf'
'==3227==AddressSanitizer: failed to intercept '__isoc99_vsnprintf'
'==3227==AddressSanitizer: failed to intercept '__isoc99_vfprintf'
'==3227==AddressSanitizer: failed to intercept 'pthread_mutexattr_getrobust_np'
'==3227==AddressSanitizer: failed to intercept 'xdr_quad_t'
'==3227==AddressSanitizer: failed to intercept 'xdr_u_quad_t'
'==3227==AddressSanitizer: failed to intercept 'xdr_destroy'
'==3227==AddressSanitizer: failed to intercept 'crypt'
'==3227==AddressSanitizer: failed to intercept 'crypt_r'
'==3227==AddressSanitizer: libc interceptors initialized
|| `[0x10007fff8000, 0x7fffffffffff]` || HighMem    ||
|| `[0x02008fff7000, 0x10007fff7fff]` || HighShadow ||
|| `[0x00008fff7000, 0x02008fff6fff]` || ShadowGap  ||
|| `[0x00007fff8000, 0x00008fff6fff]` || LowShadow  ||
|| `[0x000000000000, 0x00007fff7fff]` || LowMem     ||
MemToShadow(shadow): 0x00008fff7000 0x000091ff6dff 0x004091ff6e00 0x02008fff6fff
redzone=16
max_redzone=2048
quarantine_size_mb=256M
thread_local_quarantine_size_kb=1024K
malloc_context_size=30
SHADOW_SCALE: 3
SHADOW_GRANULARITY: 8
SHADOW_OFFSET: 0x7fff8000
==3227==Installed the sigaction for signal 11
==3227==Installed the sigaction for signal 7
==3227==Installed the sigaction for signal 8

Program received signal SIGSEGV, Segmentation fault.
do_lookup_x (undef_name=undef_name@entry=0x74bcebe18a76 "pthread_getspecific", new_hash=new_hash@entry=1644473746, old_hash=old_hash@entry=0x7fff2855a620, ref=0x74bcebe03c40, result=result@entry=0x7fff2855a630, scope=<optimized out>, i=0, version=0x74bce9ec9240, flags=1, skip=<optimized out>, type_class=1, undef_map=0x74bcec991170) at ./elf/dl-lookup.c:403
403	./elf/dl-lookup.c: No such file or directory.
(gdb) info stack   
#0  do_lookup_x (undef_name=undef_name@entry=0x74bcebe18a76 "pthread_getspecific", new_hash=new_hash@entry=1644473746, 
    old_hash=old_hash@entry=0x7fff2855a620, ref=0x74bcebe03c40, result=result@entry=0x7fff2855a630, scope=<optimized out>, 
    i=0, version=0x74bce9ec9240, flags=1, skip=<optimized out>, type_class=1, undef_map=0x74bcec991170)
    at ./elf/dl-lookup.c:403
#1  0x000074bcec9a5211 in _dl_lookup_symbol_x (undef_name=0x74bcebe18a76 "pthread_getspecific", 
    undef_map=undef_map@entry=0x74bcec991170, ref=ref@entry=0x7fff2855a6c0, symbol_scope=<optimized out>, 
    version=0x74bce9ec9240, type_class=type_class@entry=1, flags=1, skip_map=0x0) at ./elf/dl-lookup.c:860
#2  0x000074bcec9abf71 in _dl_fixup (l=0x74bcec991170, reloc_arg=102) at ./elf/dl-runtime.c:95
#3  0x000074bcec9aedae in _dl_runtime_resolve_xsavec () at ../sysdeps/x86_64/dl-trampoline.h:126
#4  0x000074bcebec36cd in __asan::GetCurrentThread () at ../../../../src/libsanitizer/asan/asan_thread.cpp:421
#5  0x000074bcebec149d in __asan::GetCurrentThreadStats () at ../../../../src/libsanitizer/asan/asan_stats.cpp:117
#6  0x000074bcebe25cec in __asan::AsanMapUnmapCallback::OnMap (size=12288, p=109951162777600, this=<optimized out>)
    at ../../../../src/libsanitizer/asan/asan_allocator.cpp:249
#7  __sanitizer::SizeClassAllocator64<__asan::AP64<__sanitizer::LocalAddressSpaceView> >::MapWithCallbackOrDie (
    name=0x74bcebefb578 "SizeClassAllocator: region info", size=12288, beg=109951162777600, 
    this=0x74bcebf34e00 <__asan::instance>)
    at ../../../../src/libsanitizer/sanitizer_common/sanitizer_allocator_primary64.h:653
#8  __sanitizer::SizeClassAllocator64<__asan::AP64<__sanitizer::LocalAddressSpaceView> >::Init (
    release_to_os_interval_ms=<optimized out>, this=0x74bcebf34e00 <__asan::instance>)
    at ../../../../src/libsanitizer/sanitizer_common/sanitizer_allocator_primary64.h:87
#9  __sanitizer::CombinedAllocator<__sanitizer::SizeClassAllocator64<__asan::AP64<__sanitizer::LocalAddressSpaceView> >, __sanitizer::LargeMmapAllocatorPtrArrayDynamic>::InitLinkerInitialized (release_to_os_interval_ms=<optimized out>, 
    this=0x74bcebf34e00 <__asan::instance>)
    at ../../../../src/libsanitizer/sanitizer_common/sanitizer_allocator_combined.h:34
#10 __asan::Allocator::InitLinkerInitialized (options=..., this=0x74bcebf34e00 <__asan::instance>)
    at ../../../../src/libsanitizer/asan/asan_allocator.cpp:341
--Type <RET> for more, q to quit, c to continue without paging--
#11 __asan::InitializeAllocator (options=...) at ../../../../src/libsanitizer/asan/asan_allocator.cpp:943
#12 0x000074bcebec0682 in __asan::AsanInitInternal () at ../../../../src/libsanitizer/asan/asan_rtl.cpp:471
#13 0x000074bcec99f5be in _dl_init (main_map=0x74bcec9d42e0, argc=2, argv=0x7fff2855ab88, env=0x7fff2855aba0)
    at ./elf/dl-init.c:102
#14 0x000074bcec9b92ca in _dl_start_user () from /lib64/ld-linux-x86-64.so.2
#15 0x0000000000000002 in ?? ()
#16 0x00007fff2855b8fc in ?? ()
#17 0x00007fff2855b90f in ?? ()
#18 0x0000000000000000 in ?? ()
```

At this point, I think trying `netpanzer --version` needs to be done using an image created where netpanzer is built with sanitization off and debug on.

**Comment by winrid** [comment]
Moved to 0.9.1 to unblock 0.9.0 since it doesn't seem to affect most users
