### ISSUE TITLE
Many indirect leaks are visible when address sanitizer is used

### ISSUE THREAD

**Issue by andy5995** [netpanzer/netpanzer#79]
After compiling with [`-fsanitize=address,undefined`](https://github.com/google/sanitizers/wiki/AddressSanitizerFlags) and fixing #66 , after successfully joining a game, I see many errors about leaks.

Log attached
[address_san.log](https://github.com/netpanzer/netpanzer/files/13866811/address_san.log)

**Comment by winrid** [comment]
hah, wow! we should fix these, even if a lot of them are UI related and we want to rebuild the existing UI - that's probably a six month project, so I think we benefit short term by improving the stability of things.

**Comment by winrid** [comment]
@andy5995 looking at the log, I am not sure we have time to fix these this week for RC7. That's a lot of issues! :)

should still do it, but might take a couple months to get through them all. I just looked at a few and they didn't seem like very obvious fixes yet.

**Comment by andy5995** [comment]
> @andy5995 looking at the log, I am not sure we have time to fix these this week for RC7. That's a lot of issues! :)

Hopefully some are in a loop and we get rid of them by fixing just one thing! ;) But I agree. It'll be nice when they're fixed though, I think it will make it easier to track down sudden client crashes.

> 
> should still do it, but might take a couple months to get through them all. I just looked at a few and they didn't seem like very obvious fixes yet.

Not obvious to me either.

Note I can't get to join a game anymore when sanitize is on. Somewhere I noted that in the last week or two, when sanitize is on, the game crashes before the main menu loads:

```
netpanzer] [andy@prometheus _sanitize](master)$ ./netpanzer
2024-01-16 00:07:25 dataDir: /home/andy/src/netpanzer/netpanzer

=================================================================
==174488==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x603000034343 at pc 0x7fd206aa4003 bp 0x7ffff15cd930 sp 0x7ffff15cd0d8
READ of size 20 at 0x603000034343 thread T0
    #0 0x7fd206aa4002 in __interceptor_memcpy /usr/src/debug/gcc/gcc/libsanitizer/sanitizer_common/sanitizer_common_interceptors.inc:899
    #1 0x559e09be31eb in filesystem::openRead(char const*) ../src/Lib/Util/FileSystem.cpp:173
    #2 0x559e09bc2d2a in Surface::loadBMP(char const*, bool) ../src/Lib/2D/Surface.cpp:1534
    #3 0x559e09d3bca3 in MenuTemplateView::doLoadBackgroundSurface(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) ../src/NetPanzer/Views/MainMenu/MenuTemplateView.cpp:315
    #4 0x559e09d3bacd in MenuTemplateView::loadMainBackgroundSurface() ../src/NetPanzer/Views/MainMenu/MenuTemplateView.cpp:310
    #5 0x559e09d4179e in MainMenuView::MainMenuView() ../src/NetPanzer/Views/MainMenu/MainMenuView.cpp:34
    #6 0x559e09b088c0 in PlayerGameManager::initializeWindowSubSystem() ../src/NetPanzer/Interfaces/PlayerGameManager.cpp:179
    #7 0x559e09b0a6a1 in PlayerGameManager::launchNetPanzerGame() ../src/NetPanzer/Interfaces/PlayerGameManager.cpp:238
    #8 0x559e09a6e8c4 in netpanzer_main(int, char**) ../src/NetPanzer/Core/main.cpp:379
    #9 0x559e09a6f2e3 in main ../src/NetPanzer/Core/main.cpp:414
    #10 0x7fd205b4dccf  (/usr/lib/libc.so.6+0x27ccf) (BuildId: 8bfe03f6bf9b6a6e2591babd0bbc266837d8f658)
    #11 0x7fd205b4dd89 in __libc_start_main (/usr/lib/libc.so.6+0x27d89) (BuildId: 8bfe03f6bf9b6a6e2591babd0bbc266837d8f658)
    #12 0x559e09a66c64 in _start (/home/andy/src/netpanzer/netpanzer/_sanitize/netpanzer+0xbc5c64) (BuildId: 01a3abbb08f0c240cb3caae3bb0d80ea7041bc2f)

0x603000034343 is located 0 bytes after 19-byte region [0x603000034330,0x603000034343)
allocated by thread T0 here:
    #0 0x7fd206b24359 in __interceptor_malloc /usr/src/debug/gcc/gcc/libsanitizer/asan/asan_malloc_linux.cpp:69
    #1 0x7fd2066b0a7a  (/usr/lib/libphysfs.so.1+0x6a7a) (BuildId: 08e4702f577e7ce0e7dafc8c32392b736e888d8e)

SUMMARY: AddressSanitizer: heap-buffer-overflow /usr/src/debug/gcc/gcc/libsanitizer/sanitizer_common/sanitizer_common_interceptors.inc:899 in __interceptor_memcpy
Shadow bytes around the buggy address:
  0x603000034080: fa fa fd fd fd fa fa fa fd fd fd fa fa fa 00 00
  0x603000034100: 00 fa fa fa fd fd fd fa fa fa fd fd fd fd fa fa
  0x603000034180: fd fd fd fd fa fa 00 00 00 fa fa fa 00 00 00 fa
  0x603000034200: fa fa 00 00 02 fa fa fa fd fd fd fa fa fa fd fd
  0x603000034280: fd fd fa fa fd fd fd fa fa fa fd fd fd fa fa fa
=>0x603000034300: 00 00 00 00 fa fa 00 00[03]fa fa fa fa fa fa fa
  0x603000034380: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x603000034400: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x603000034480: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x603000034500: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x603000034580: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
==174488==ABORTING
[netpanzer] [andy@prometheus _sanitize](master)$ nano ~/.netpanzer/config/client.cfg 
[netpanzer] [andy@prometheus _sanitize](master)$ ./netpanzer
2024-01-16 00:07:48 dataDir: /home/andy/src/netpanzer/netpanzer

=================================================================
==174629==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x603000032cc3 at pc 0x7f6a7b782003 bp 0x7fff62f91f60 sp 0x7fff62f91708
READ of size 20 at 0x603000032cc3 thread T0
    #0 0x7f6a7b782002 in __interceptor_memcpy /usr/src/debug/gcc/gcc/libsanitizer/sanitizer_common/sanitizer_common_interceptors.inc:899
    #1 0x55cf8bf3a1eb in filesystem::openRead(char const*) ../src/Lib/Util/FileSystem.cpp:173
    #2 0x55cf8bf19d2a in Surface::loadBMP(char const*, bool) ../src/Lib/2D/Surface.cpp:1534
    #3 0x55cf8c092ca3 in MenuTemplateView::doLoadBackgroundSurface(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) ../src/NetPanzer/Views/MainMenu/MenuTemplateView.cpp:315
    #4 0x55cf8c092acd in MenuTemplateView::loadMainBackgroundSurface() ../src/NetPanzer/Views/MainMenu/MenuTemplateView.cpp:310
    #5 0x55cf8c09879e in MainMenuView::MainMenuView() ../src/NetPanzer/Views/MainMenu/MainMenuView.cpp:34
    #6 0x55cf8be5f8c0 in PlayerGameManager::initializeWindowSubSystem() ../src/NetPanzer/Interfaces/PlayerGameManager.cpp:179
    #7 0x55cf8be616a1 in PlayerGameManager::launchNetPanzerGame() ../src/NetPanzer/Interfaces/PlayerGameManager.cpp:238
    #8 0x55cf8bdc58c4 in netpanzer_main(int, char**) ../src/NetPanzer/Core/main.cpp:379
    #9 0x55cf8bdc62e3 in main ../src/NetPanzer/Core/main.cpp:414
    #10 0x7f6a7a82bccf  (/usr/lib/libc.so.6+0x27ccf) (BuildId: 8bfe03f6bf9b6a6e2591babd0bbc266837d8f658)
    #11 0x7f6a7a82bd89 in __libc_start_main (/usr/lib/libc.so.6+0x27d89) (BuildId: 8bfe03f6bf9b6a6e2591babd0bbc266837d8f658)
    #12 0x55cf8bdbdc64 in _start (/home/andy/src/netpanzer/netpanzer/_sanitize/netpanzer+0xbc5c64) (BuildId: 01a3abbb08f0c240cb3caae3bb0d80ea7041bc2f)

0x603000032cc3 is located 0 bytes after 19-byte region [0x603000032cb0,0x603000032cc3)
allocated by thread T0 here:
    #0 0x7f6a7b802359 in __interceptor_malloc /usr/src/debug/gcc/gcc/libsanitizer/asan/asan_malloc_linux.cpp:69
    #1 0x7f6a7b38ea7a  (/usr/lib/libphysfs.so.1+0x6a7a) (BuildId: 08e4702f577e7ce0e7dafc8c32392b736e888d8e)

SUMMARY: AddressSanitizer: heap-buffer-overflow /usr/src/debug/gcc/gcc/libsanitizer/sanitizer_common/sanitizer_common_interceptors.inc:899 in __interceptor_memcpy
Shadow bytes around the buggy address:
  0x603000032a00: fa fa fd fd fd fa fa fa fd fd fd fa fa fa 00 00
  0x603000032a80: 00 fa fa fa fd fd fd fa fa fa fd fd fd fd fa fa
  0x603000032b00: fd fd fd fd fa fa 00 00 00 fa fa fa 00 00 00 fa
  0x603000032b80: fa fa 00 00 02 fa fa fa fd fd fd fa fa fa fd fd
  0x603000032c00: fd fd fa fa fd fd fd fa fa fa fd fd fd fa fa fa
=>0x603000032c80: 00 00 00 00 fa fa 00 00[03]fa fa fa fa fa fa fa
  0x603000032d00: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x603000032d80: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x603000032e00: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x603000032e80: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x603000032f00: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
==174629==ABORTING
```

Note that all these leaks would probably be visible without a "sanitized" build using valgrind.

**Comment by winrid** [comment]
Oh I see, fn_start is just the start address of `fn`. okay... thought it was the start of a filename :D
